export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Notice({ params }) {

    const { id, slug } = params

    return (
        <></>
    )
}